"""Voice Option

Revision ID: 1903a7009519
Revises: ebe66ef2ec95
Create Date: 2026-09-06 02:00:17.230900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database import VoiceOptionModel
from enum_model import QuartetRangeEnum, SingerVoiceEnum

# revision identifiers, used by Alembic.
revision: str = "1903a7009519"
down_revision: Union[str, Sequence[str], None] = "ebe66ef2ec95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_option",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "quartet_range",
            sa.Enum("SSAA", "SATB", "TTBB", name="quartetrangeenum"),
            nullable=False,
        ),
        sa.Column(
            "singer_voice",
            sa.Enum("TENOR", "LEAD", "BARI", "BASS", name="singervoiceenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    quartet_options = [
        QuartetRangeEnum.SSAA,
        QuartetRangeEnum.SATB,
        QuartetRangeEnum.TTBB,
    ]
    voice_options = [
        SingerVoiceEnum.TENOR,
        SingerVoiceEnum.LEAD,
        SingerVoiceEnum.BARI,
        SingerVoiceEnum.BASS,
    ]
    op.execute(
        sa.insert(VoiceOptionModel).values(
            [
                {"quartet_range": quartet_range, "singer_voice": singer_voice}
                for quartet_range in quartet_options
                for singer_voice in voice_options
            ]
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voice_option")
    # ### end Alembic commands ###
