"""Singer Voice XRef

Revision ID: c142588380a8
Revises: 1903a7009519
Create Date: 2026-09-06 02:21:30.709734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c142588380a8"
down_revision: Union[str, Sequence[str], None] = "1903a7009519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "singer_voice_option_xref",
        sa.Column("singer_id", sa.Integer(), nullable=False),
        sa.Column("voice_option_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["singer_id"], ["singer.id"], name="foreign_singer_id"),
        sa.ForeignKeyConstraint(
            ["voice_option_id"], ["voice_option.id"], name="foreign_voice_id"
        ),
        sa.PrimaryKeyConstraint("singer_id", "voice_option_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("singer_voice_option_xref")
    # ### end Alembic commands ###
